from app.models.analysis_run import AnalysisRun
from app.services.evidence_redaction_service import redact_text

GITHUB_COMMENT_MARKER_TEMPLATE = "<!-- ai-quality-gate:analysis-run:{analysis_run_id} -->"


def build_final_report(run: AnalysisRun, ai_review_json: dict) -> str:
    if run.status.value == "error" and run.decision is None:
        return build_operational_error_report(run)

    decision = run.decision.value.upper() if run.decision else "NO DECISION"
    lines = [
        f"# AI Quality Gate: {decision}",
        "",
        f"**Gate Decision:** {decision}",
    ]
    if run.score is not None:
        lines.extend(["", f"**Score:** {int(run.score)}/100"])

    summary = _summary_for(run, ai_review_json)
    lines.extend(["", "## Summary", "", summary])
    lines.extend(_pillar_section("Coverage", run.coverage_result_json, ai_review_json.get("coverage_assessment")))
    lines.extend(_pillar_section("Security", run.security_result_json, ai_review_json.get("security_assessment")))
    lines.extend(
        _pillar_section(
            "Technical Debt",
            run.technical_debt_result_json,
            ai_review_json.get("technical_debt_assessment"),
        )
    )
    lines.extend(_list_section("Blocking Reasons", _blocking_reasons(run, ai_review_json)))
    lines.extend(_list_section("Suggestions", _suggestions(run, ai_review_json)))
    lines.extend(["", "---", "Generated by PR Quality Gate Dashboard."])
    return "\n".join(lines).strip() + "\n"


def build_operational_error_report(run: AnalysisRun) -> str:
    lines = [
        "# AI Quality Gate: OPERATIONAL ERROR",
        "",
        "**Gate Decision:** No decision",
        "",
        "## Summary",
        "",
        run.error_message or "A required gate could not complete.",
        "",
        "## Coverage",
        "",
        _snapshot_summary(run.coverage_result_json),
        "",
        "## Security",
        "",
        _snapshot_summary(run.security_result_json),
        "",
        "## Technical Debt",
        "",
        _snapshot_summary(run.technical_debt_result_json),
        "",
        "---",
        "Generated by PR Quality Gate Dashboard.",
    ]
    return "\n".join(lines).strip() + "\n"


def build_github_comment_body(run: AnalysisRun) -> str:
    marker = GITHUB_COMMENT_MARKER_TEMPLATE.format(analysis_run_id=run.id)
    report = run.final_report_markdown or build_final_report(run, run.ai_review_json)
    return f"{marker}\n\n{redact_text(report)}"


def github_comment_marker(run: AnalysisRun) -> str:
    return GITHUB_COMMENT_MARKER_TEMPLATE.format(analysis_run_id=run.id)


def _summary_for(run: AnalysisRun, ai_review_json: dict) -> str:
    if ai_review_json.get("status") == "generated" and ai_review_json.get("summary"):
        return str(ai_review_json["summary"])
    if ai_review_json.get("status") == "skipped":
        return "AI review was skipped, so this report summarizes deterministic gate evidence."
    if ai_review_json.get("status") == "error":
        return "AI review could not be generated, so this report summarizes deterministic gate evidence."
    if run.decision and run.decision.value == "pass":
        return "All required gates completed and passed their configured policies."
    return "One or more required gates completed and failed their configured policies."


def _pillar_section(title: str, snapshot: dict, assessment: str | None) -> list[str]:
    lines = ["", f"## {title}", "", assessment or _snapshot_summary(snapshot)]
    reasons = _string_list(snapshot.get("blocking_reasons"))
    if reasons:
        lines.extend(["", "Blocking reasons:"])
        lines.extend(f"- {reason}" for reason in reasons)
    suggestions = _string_list(snapshot.get("suggestions"))
    if suggestions:
        lines.extend(["", "Suggestions:"])
        lines.extend(f"- {suggestion}" for suggestion in suggestions)
    return lines


def _snapshot_summary(snapshot: dict) -> str:
    if not snapshot:
        return "No snapshot was produced."
    status = snapshot.get("status", "not reported")
    details = [f"Status: {status}."]
    for key in (
        "total_coverage",
        "base_coverage",
        "pr_coverage",
        "changed_files_coverage",
        "coverage_drop",
        "critical",
        "high",
        "medium",
        "low",
        "score",
    ):
        if key in snapshot:
            details.append(f"{key}: {snapshot[key]}.")
    return " ".join(details)


def _blocking_reasons(run: AnalysisRun, ai_review_json: dict) -> list[str]:
    reasons = _string_list(ai_review_json.get("blocking_reasons"))
    for snapshot in (
        run.coverage_result_json,
        run.security_result_json,
        run.technical_debt_result_json,
    ):
        reasons.extend(_string_list(snapshot.get("blocking_reasons")))
    for finding in run.findings:
        if finding.blocking:
            reasons.append(finding.title)
    return _unique(reasons)


def _suggestions(run: AnalysisRun, ai_review_json: dict) -> list[str]:
    suggestions = _string_list(ai_review_json.get("suggestions"))
    for snapshot in (
        run.coverage_result_json,
        run.security_result_json,
        run.technical_debt_result_json,
    ):
        suggestions.extend(_string_list(snapshot.get("suggestions")))
    return _unique(suggestions)


def _list_section(title: str, values: list[str]) -> list[str]:
    lines = ["", f"## {title}", ""]
    if not values:
        return lines + ["None."]
    return lines + [f"- {value}" for value in values]


def _string_list(value) -> list[str]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, str)]


def _unique(values: list[str]) -> list[str]:
    seen = set()
    unique_values = []
    for value in values:
        if value not in seen:
            seen.add(value)
            unique_values.append(value)
    return unique_values
